force-app/main/default/objects/Log__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/logging/LoggerTest.cls
@IsTest
private class LoggerTest {

	@IsTest
	private static void debug() {
		// Setup
		enableLogEvents(System.today());

		Id contextId = 'a2R1T0000034dUTUAY';
		String message = '{0}=={1}:{2}';
		List<Object> values = new List<Object>{ 1, '2', false };

        Logger logger = new Logger();

		// Execute
        logger.debug(message, values, contextId);

		// Verify
		Log__e log = logger.currentEvent;

		System.assertEquals('1==2:false', log.Message__c);
		System.assertEquals(LoggingLevel.DEBUG.name(), log.Level__c);
		System.assertEquals(contextId, log.Context__c);
		System.assertEquals(thisClassName(), log.ClassName__c);
		System.assertEquals('debug', log.Method__c);
		System.assertEquals(16, log.LineNumber__c);
	}


	@IsTest
	private static void error() {
		// Setup
        enableLogEvents(System.today());

        Logger logger = new Logger();

		// Execute
        logger.error('');

        System.debug('logger.currentEvent: ' + logger.currentEvent);

		// Verify
		System.assertEquals(LoggingLevel.ERROR.name(), logger.currentEvent.Level__c);
	}


	@IsTest
	private static void timestampWhenNoContextId() {
		// Setup
        enableLogEvents(System.today());
        Logger logger = new Logger();

		// Execute
        logger.debug('');

		// Verify
		System.assertNotEquals(null, logger.currentEvent.Context__c);
	}

	@IsTest
	private static void noEventsSendWhenDisabled() {
		// Execute
        Logger logger = new Logger();
        logger.debug('');

		// Verify
		System.assertEquals(null, logger.currentEvent);
	}

	@IsTest
	private static void noEventsWhenExpired() {
		// Setup
        enableLogEvents(yesterDay());
        Logger logger = new Logger();

		// Execute
        logger.debug('');

		// Verify
		System.assertEquals(null, logger.currentEvent);
	}

	private static void enableLogEvents(Date day) {
		insert new LoggerSetting__c(SetupOwnerId = UserInfo.getUserId(), dat_LogViaEvents__c = day);
	}


	private static Date yesterDay() {
		return System.today().addDays(-1);
	}

	private static String thisClassName() {
		String ns = [SELECT NamespacePrefix FROM Organization].NamespacePrefix + '.';
		return LoggerTest.class.getName().removeStart(ns);
	}
}